repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python3]
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python3 -m unittest discover
        language: python
        types: [python3]
        args: ["-p'test_*.py'"]
        pass_filenames: false
        stage: [commit]
